---
title: "Dockerized Cranvas"
author: "Misha Lisovich"
date: 2019-12-26
categories: ["R", "datavis"]
tags: ["R", "rlang", "datavis", "interactive visualization", "eda"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


**TLDR**: The legendary [Cranvas](https://github.com/ggobi/cranvas) dataviz library, now in a [Docker container](https://img.shields.io/docker/cloud/build/mul118/docker-cranvas-ggobi). 

Interactive statistical graphics are incredibly useful both as an Interactive Exploartory Data Analysis (IEDA) tool and as a visual 'debugger' for building machine learning models and complex data science products such as search/recommenders, text tagging, custom playlist generators, etc. Unfortunately, it's also somewhat of a [lost art](https://yihui.name/en/2017/12/good-old-ideas/), and while modern interactive graphics alternatives exist via [interactive Shiny plots](https://shiny.rstudio.com/articles/plot-interaction.html), [linked Plotly graphics](https://plotly-r.com/), etc, in my experience none have approached the power, simplicity, and performance provided by Cranvas's old-school (Desktop/Qt) linked IEDA primitives.

Part of the reason for Cranvas's lack of reach is the high barrier to entry - it's [devilishly complex to install](https://github.com/tsieger/idendro/wiki), and virtually impossible on latest MacOS and Windows systems. 

This project aims to lower the barrier to entry by: 

1. Wrapping Cranvas & GGobi in a stable, containerized Linux GUI environment that can be accessed through the browser and run on any OS with Docker installed, and 
2. Handling the complex Cranvas build process, providing an immediately-useful base image that can also be modified/extended.

While Cranvas may not be 'the future', the IEDA ideas behind it definitely are, and it's uniquely useful at present.  It is the my hope that this project can introduce practicing Data Scientists & Analysts to the benefits and potential of IEDA, and play a (small) role in incorporating it into the next generation of DS platforms. 


## The Project

The project is bundled into a batteries-included Docker image containing: 

- A browser-accessible Ubuntu installation 
- Rstudio Server with pre-installed tidyverse packages
- [Cranvas](https://github.com/ggobi/cranvas) interactive exploratory data analysis library 
- [GGobi](http://ggobi.org/)/[rggobi](https://github.com/ggobi/rggobi) high-dimensional visualization program.
- [idendro](https://github.com/tsieger/idendro) Cranvas extension enabling interactive exploration of heirarchical clustering dendrograms.


## Quick Start

Install Docker. Then, from command line, run

``` bash
docker run -itd -p 6080:80 -v [YOUR LOCAL WORKING DIRECTORY]:/root/work mul118/docker-cranvas-ggobi
```

The startup process will take about *5 minutes* the first time. Once the container is running, browse to http://127.0.0.1:6080/. Open the terminal (Start > System Tools > LXTerminal) and type:

``` bash
/startup_cranvas_patch.sh
```

When the patch finishes applying, open Rstudio and attach the cranvas library. Enjoy!


## Resources
  
### Cranvas 

As far as I know, Cranvas does not have a cohesive vignette (a large part of its hipster charm). My recommendation is to go through the Mondrian tips tutorial slides and use the provided companion code reproduce the tutorial using Cranvas.


- Tutorial:  [slides](http://www.interactivegraphics.org/Slides.html) | [code](https://www.github.com/mul118/docker-cranvas-ggobi/examples/cranvas_intro.R)
- [Cranvas Cheatsheet](https://www.github.com/mul118/docker-cranvas-ggobi/examples/cranvas_cheatsheet.Rmd)
- [Package Docs](https://www.rdocumentation.org/packages/cranvas) - see qscatter, qhist, qbar, qparallel for intro examples
- [Cranvas Overview Paper](https://arxiv.org/pdf/1409.7256.pdf) 

# Extensions:

- [Qtime](https://pdfs.semanticscholar.org/f8b5/26fb936fc25ca10c004deb4db667c29f9c5a.pdf): Cranvas Time-series interactions (see p 32)
- *Visualizing Statistical Models*: [paper](http://had.co.nz/stat645/model-vis.pdf) | [Cranvas code](https://www.github.com/mul118/docker-cranvas-ggobi)
- *Idendro*: [Intro & Sample Code](https://github.com/tsieger/idendro) | [Full Vignette](https://github.com/tsieger/idendro/blob/master/inst/doc/idendro.pdf)
- Qtour - high-dimensional tours
- Qmval - missing values

### Statistical Graphics

- [Mondrian](http://mondrian.theusrus.de/) - Interactive dynamic graphics GUI
  - Tutorial/case studies: [slides](http://www.interactivegraphics.org/Slides.html)
  - Book: [Dynamic Graphics for Interactive Data Exploration](http://mondrian.theusrus.de/)
  


- *GGobi*: [Resources](http://www.ggobi.org/docs) | [Manual](http://www.ggobi.org/docs/manual.pdf) | [Rggobi Intro](http://www.ggobi.org/rggobi/introduction.pdf)


## Build

To build the docker image, navigate to the root project directory and type:


``` bash
docker build -t docker-cranvas-ggobi .
```
